In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/yasserh/breast-cancer-dataset/breast-cancer.csv


In [2]:
import pandas as pd 
import numpy as np

In [3]:
data=pd.read_csv("/kaggle/input/datasets/yasserh/breast-cancer-dataset/breast-cancer.csv")

In [4]:
data.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [5]:
data.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [6]:
data.isna().sum()

id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [7]:
data.duplicated().sum()

np.int64(0)

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [9]:
data['diagnosis'].unique()

array(['M', 'B'], dtype=object)

**Encoding**

In [10]:
data["diagnosis"] = data["diagnosis"].map({
    "M": 1,
    "B": 0
})

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# models importing

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

# Evaluation metrics importing

In [13]:
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
    roc_curve
)


In [14]:
scaler=StandardScaler()

In [15]:
x=data.drop(columns="diagnosis",axis=1)
y=data['diagnosis']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [16]:
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [17]:
model_scaling={
    "logistic_regression":LogisticRegression(max_iter=1000),
    "KNN": KNeighborsClassifier(
        metric="euclidean",
        n_neighbors=5,
        weights="uniform"
    ),
    "svm":SVC()
}
for name, model in model_scaling.items():
    print("=" * 50)
    print(f"Model: {name}")
    print("=" * 50)

    model.fit(x_train_scaled, y_train)
    y_pred = model.predict(x_test_scaled)

    print(f"Accuracy       : {accuracy_score(y_test, y_pred):.4f}")
    print(f"F1 Score       : {f1_score(y_test, y_pred):.4f}")
    print(f"Precision      : {precision_score(y_test, y_pred):.4f}")
    print(f"Recall         : {recall_score(y_test, y_pred):.4f}")
    print(f"ROC-AUC Score  : {roc_auc_score(y_test, y_pred):.4f}")

    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

    print("\n")

Model: logistic_regression
Accuracy       : 0.9737
F1 Score       : 0.9647
Precision      : 0.9762
Recall         : 0.9535
ROC-AUC Score  : 0.9697

Confusion Matrix:
[[70  1]
 [ 2 41]]

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.99      0.98        71
           1       0.98      0.95      0.96        43

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



Model: KNN
Accuracy       : 0.9474
F1 Score       : 0.9302
Precision      : 0.9302
Recall         : 0.9302
ROC-AUC Score  : 0.9440

Confusion Matrix:
[[68  3]
 [ 3 40]]

Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.96      0.96        71
           1       0.93      0.93      0.93        43

    accuracy                           0.95       114
   macro avg       0.94      0.94      0.94       1

In [18]:
models={
    "decisiontree":DecisionTreeClassifier(),
    "Gnaive_bayes":GaussianNB(),
    "random_forest":RandomForestClassifier()
}
for name,model in models.items():
    print("=" * 50)
    print(f"Model: {name}")
    print("=" * 50)

    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)

    print(f"Accuracy       : {accuracy_score(y_test, y_pred):.4f}")
    print(f"F1 Score       : {f1_score(y_test, y_pred):.4f}")
    print(f"Precision      : {precision_score(y_test, y_pred):.4f}")
    print(f"Recall         : {recall_score(y_test, y_pred):.4f}")
    print(f"ROC-AUC Score  : {roc_auc_score(y_test, y_pred):.4f}")

    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

    print("\n")

Model: decisiontree
Accuracy       : 0.9386
F1 Score       : 0.9195
Precision      : 0.9091
Recall         : 0.9302
ROC-AUC Score  : 0.9369

Confusion Matrix:
[[67  4]
 [ 3 40]]

Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.94      0.95        71
           1       0.91      0.93      0.92        43

    accuracy                           0.94       114
   macro avg       0.93      0.94      0.93       114
weighted avg       0.94      0.94      0.94       114



Model: Gnaive_bayes
Accuracy       : 0.6140
F1 Score       : 0.0000
Precision      : 0.0000
Recall         : 0.0000
ROC-AUC Score  : 0.4930

Confusion Matrix:
[[70  1]
 [43  0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.62      0.99      0.76        71
           1       0.00      0.00      0.00        43

    accuracy                           0.61       114
   macro avg       0.31      0.49      0.38      

**overall our SVC is performing best then Logistic Regression and Random Forest**

# Hypertunning of models

In [19]:
from sklearn.model_selection import GridSearchCV
knn=KNeighborsClassifier()
classifier = GridSearchCV(
    estimator=knn,
    param_grid={
        "n_neighbors": [3, 5, 7, 9, 11, 13],
        "weights": ["uniform", "distance"],
        "metric": ["euclidean", "manhattan", "minkowski"]
    },
    cv=5,
    return_train_score=True,
    scoring="accuracy"
)

classifier.fit(x_train_scaled, y_train)

result = pd.DataFrame(classifier.cv_results_)

print(classifier.best_params_)
print(classifier.best_score_)

{'metric': 'euclidean', 'n_neighbors': 5, 'weights': 'uniform'}
0.9626373626373628


In [20]:
svc=SVC()
param_grid = {
    "C": [0.1, 1, 10, 100, 1000],
    "kernel": ["linear", "rbf", "poly"],
    "gamma": ["scale", "auto", 0.1, 0.01, 0.001]
}
svc_classifier=GridSearchCV(estimator=svc,param_grid={
    "C": [0.1, 1, 10, 100, 1000],
    "kernel": ["linear", "rbf", "poly"],
    "gamma": ["scale", "auto", 0.1, 0.01, 0.001]
},cv=5,return_train_score=False,scoring="accuracy")
svc_classifier.fit(x_train_scaled,y_train)
result_svc=svc_classifier.cv_results_
print(svc_classifier.best_params_)

{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}


In [21]:
best_svc = svc_classifier.best_estimator_

In [22]:
model_svc={
    "svc":best_svc
}
for name,model in model_svc.items():
    print("=" * 50)
    print(f"Model: {name}")
    print("=" * 50)

    model.fit(x_train_scaled, y_train)
    y_pred = model.predict(x_test_scaled)

    print(f"Accuracy       : {accuracy_score(y_test, y_pred):.4f}")
    print(f"F1 Score       : {f1_score(y_test, y_pred):.4f}")
    print(f"Precision      : {precision_score(y_test, y_pred):.4f}")
    print(f"Recall         : {recall_score(y_test, y_pred):.4f}")
    print(f"ROC-AUC Score  : {roc_auc_score(y_test, y_pred):.4f}")

    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

    print("\n")

Model: svc
Accuracy       : 0.9737
F1 Score       : 0.9647
Precision      : 0.9762
Recall         : 0.9535
ROC-AUC Score  : 0.9697

Confusion Matrix:
[[70  1]
 [ 2 41]]

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.99      0.98        71
           1       0.98      0.95      0.96        43

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114





# Stacking (ensemble learning)

In [23]:
from sklearn.ensemble import StackingClassifier

In [24]:
base_learners = [
    ("lr", LogisticRegression(max_iter=1000)),
    ("knn", KNeighborsClassifier(n_neighbors=7)),
    ("dt", DecisionTreeClassifier(max_depth=5, random_state=42)),
    ("rf", RandomForestClassifier(random_state=42)),
    ("svm", SVC(probability=True))
]
final_learners=[LogisticRegression(max_iter=1000),SVC(probability=True),RandomForestClassifier(random_state=42)
               , KNeighborsClassifier(n_neighbors=7),DecisionTreeClassifier(max_depth=5, random_state=42)]
for model in final_learners:
    stacking_classifier = StackingClassifier(
        estimators=base_learners,
        final_estimator=model,
        cv=5
    )
    
    stacking_classifier.fit(x_train_scaled, y_train)
    
    y_pred_stacking = stacking_classifier.predict(x_test_scaled)
    
    print(f"Accuracy       : {accuracy_score(y_test, y_pred_stacking):.4f}")
    print(f"F1 Score       : {f1_score(y_test, y_pred_stacking):.4f}")
    print(f"Precision      : {precision_score(y_test, y_pred_stacking):.4f}")
    print(f"Recall         : {recall_score(y_test, y_pred_stacking):.4f}")
    print(f"ROC-AUC Score  : {roc_auc_score(y_test, y_pred_stacking):.4f}")
    
    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_pred_stacking))
    
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred_stacking))

Accuracy       : 0.9737
F1 Score       : 0.9647
Precision      : 0.9762
Recall         : 0.9535
ROC-AUC Score  : 0.9697

Confusion Matrix:
[[70  1]
 [ 2 41]]

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.99      0.98        71
           1       0.98      0.95      0.96        43

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

Accuracy       : 0.9737
F1 Score       : 0.9647
Precision      : 0.9762
Recall         : 0.9535
ROC-AUC Score  : 0.9697

Confusion Matrix:
[[70  1]
 [ 2 41]]

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.99      0.98        71
           1       0.98      0.95      0.96        43

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97    

**The stacking ensemble did not improve performance because the base learners already produced highly similar predictions. On this dataset, SVM remained the best-performing classifier with an accuracy of 98.25%, illustrating that stacking is most effective when base models have complementary strengths rather than nearly identical behavior.**

# conclusion

Our svc model worked best among all the indivisual model as well as all the model combined and trained indivisually
stacking method.